// Landing page components barrel export
export { GalaxyView } from './GalaxyView';
export { HeroSection } from './HeroSection';
export { SocialProofSection } from './SocialProofSection';
export { TimelineSection } from './TimelineSection';
export { SafeSpaceSection } from './SafeSpaceSection';
export { FeaturesBento } from './FeaturesBento';
export { SundayReviewSection } from './SundayReviewSection';
export { CTASection } from './CTASection';
export { MinimalFooter } from './MinimalFooter';
